/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

/**
 *
 * @author Acer Aspire Lite 15
 */
import config.SessionManager; // Menggunakan SessionManager proyek ini
import login.halaman_login;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter; // Tetap perlu untuk klik label
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
// Import semua panel Anda
import admin.beranda;
import admin.kategori_menu;
import admin.daftar_menu;
import admin.daftar_metode_pembayaran;
import admin.daftar_user;
import admin.laporan_transaksi;

public class dashboard_admin extends javax.swing.JFrame {

    /**
     * Creates new form dashboard_admin
     */
    public dashboard_admin() {
        initComponents();
        
        label_username.setText(SessionManager.getUsername());
        label_role.setText(SessionManager.getRole().toUpperCase());
        
        // 2. Mengatur Layout panel_utama_A (Tetap sama)
        panel_utama_A.setLayout(new BorderLayout());
        
        // 3. Menampilkan panel 'beranda' sebagai default (Tetap sama)
        // Kita ganti nama methodnya agar sama seperti contoh Anda
        showPanel(new beranda());
        
        // 4. Menambahkan listener ke label judul (Tetap sama)
        // (Ini adalah satu-satunya listener yang kita pasang manual
        // karena label tidak punya ...ActionPerformed seperti tombol)
        label_dashboard_admin.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Saat label diklik, muat panel beranda
                showPanel(new beranda());
            }
        });
        
        
    }
    
    private void showPanel(JPanel panel) {
        panel_utama_A.removeAll();
        panel_utama_A.add(panel, BorderLayout.CENTER);
        panel_utama_A.revalidate();
        panel_utama_A.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_dashboard_admin = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        label_role = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_daftar_menu = new javax.swing.JButton();
        btn_beranda = new javax.swing.JButton();
        btn_kategori = new javax.swing.JButton();
        btn_laporan_transaksi = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        btn_daftar_user = new javax.swing.JButton();
        panel_utama_A = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("=");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 80, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 60));

        label_dashboard_admin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        label_dashboard_admin.setForeground(new java.awt.Color(255, 255, 255));
        label_dashboard_admin.setText("DASHBOARD ADMIIN");
        jPanel1.add(label_dashboard_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 630, 80));

        btn_logout.setBackground(new java.awt.Color(0, 0, 102));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LOG OUT");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 40, 150, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("POSISI :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 60, 110, 40));

        label_username.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_username.setText("KASIR1");
        label_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 20, 190, 40));

        label_role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_role.setForeground(new java.awt.Color(255, 255, 255));
        label_role.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_role.setText("ADMIN");
        label_role.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(label_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(1530, 60, 190, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("USERNAME :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 20, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 120));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_daftar_menu.setBackground(new java.awt.Color(153, 153, 153));
        btn_daftar_menu.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_daftar_menu.setForeground(new java.awt.Color(0, 0, 0));
        btn_daftar_menu.setText("DAFTAR MENU");
        btn_daftar_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftar_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn_daftar_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 50));

        btn_beranda.setBackground(new java.awt.Color(153, 153, 153));
        btn_beranda.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_beranda.setForeground(new java.awt.Color(0, 0, 0));
        btn_beranda.setText("BERANDA");
        btn_beranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_berandaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 50));

        btn_kategori.setBackground(new java.awt.Color(153, 153, 153));
        btn_kategori.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_kategori.setForeground(new java.awt.Color(0, 0, 0));
        btn_kategori.setText("KATEGORI MENU");
        btn_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kategoriActionPerformed(evt);
            }
        });
        jPanel2.add(btn_kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 200, 50));

        btn_laporan_transaksi.setBackground(new java.awt.Color(153, 153, 153));
        btn_laporan_transaksi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_laporan_transaksi.setForeground(new java.awt.Color(0, 0, 0));
        btn_laporan_transaksi.setText("TRANSAKSI");
        btn_laporan_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporan_transaksiActionPerformed(evt);
            }
        });
        jPanel2.add(btn_laporan_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 50));

        btn_pembayaran.setBackground(new java.awt.Color(153, 153, 153));
        btn_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_pembayaran.setForeground(new java.awt.Color(0, 0, 0));
        btn_pembayaran.setText("METODE PEMBAYARAN");
        btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembayaranActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 50));

        btn_daftar_user.setBackground(new java.awt.Color(153, 153, 153));
        btn_daftar_user.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_daftar_user.setForeground(new java.awt.Color(0, 0, 0));
        btn_daftar_user.setText("DAFTAR USER");
        btn_daftar_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_daftar_userActionPerformed(evt);
            }
        });
        jPanel2.add(btn_daftar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 220, 960));

        panel_utama_A.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_utama_ALayout = new javax.swing.GroupLayout(panel_utama_A);
        panel_utama_A.setLayout(panel_utama_ALayout);
        panel_utama_ALayout.setHorizontalGroup(
            panel_utama_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1660, Short.MAX_VALUE)
        );
        panel_utama_ALayout.setVerticalGroup(
            panel_utama_ALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        getContentPane().add(panel_utama_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 1660, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", 
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (response == JOptionPane.YES_OPTION) {
            SessionManager.clearSession(); // Hapus sesi
            new halaman_login().setVisible(true); // Buka login
            this.dispose(); // Tutup dashboard ini
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_berandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_berandaActionPerformed
        // TODO add your handling code here:
        showPanel(new beranda());
    }//GEN-LAST:event_btn_berandaActionPerformed

    private void btn_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kategoriActionPerformed
        // TODO add your handling code here:
        showPanel(new kategori_menu());
    }//GEN-LAST:event_btn_kategoriActionPerformed

    private void btn_daftar_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftar_menuActionPerformed
        // TODO add your handling code here:
        showPanel(new daftar_menu());
    }//GEN-LAST:event_btn_daftar_menuActionPerformed

    private void btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembayaranActionPerformed
        // TODO add your handling code here:
        showPanel(new daftar_metode_pembayaran());
    }//GEN-LAST:event_btn_pembayaranActionPerformed

    private void btn_daftar_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_daftar_userActionPerformed
        // TODO add your handling code here:
        showPanel(new daftar_user());
    }//GEN-LAST:event_btn_daftar_userActionPerformed

    private void btn_laporan_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporan_transaksiActionPerformed
        // TODO add your handling code here:
        showPanel(new laporan_transaksi());
    }//GEN-LAST:event_btn_laporan_transaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_beranda;
    private javax.swing.JButton btn_daftar_menu;
    private javax.swing.JButton btn_daftar_user;
    private javax.swing.JButton btn_kategori;
    private javax.swing.JButton btn_laporan_transaksi;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_dashboard_admin;
    private javax.swing.JLabel label_role;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel panel_utama_A;
    // End of variables declaration//GEN-END:variables
}
